config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users

  namespace :super_admin do
    get '/', to: 'dashboard#index'
    resources :users
    resources :roles, except: [:show]
  end

  resources :projects do
    resources :rfqs, except: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string
#  number     :string
#  jobsite    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Project < ApplicationRecord
  has_many :rfqs
end

app/models/rfq.rb
class Rfq < ApplicationRecord
  belongs_to :project

  STATUS = ['Active', 'Archived', 'Blocked']
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id            :integer          not null, primary key
#  name          :string
#  resource_type :string
#  resource_id   :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = 'Successfully create a new Project'
      redirect_to projects_path
    else
      flash[:error] = 'Something went wrong, can not create Project'
      redirect_to new_project_path
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:success] = 'Successfully updated Project'
      redirect_to projects_path
    else
      flash[:error] = 'Something went wrong, can not update Project'
      redirect_to edit_project_path(@project)
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = 'Successfully deleted Project'
      redirect_to projects_path
    else
      flash[:error] = 'Something went wrong, can not delete Project'
      redirect_to projects_path
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :number, :jobsite)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/rfqs_controller.rb
class RfqsController < ApplicationController
  before_action :set_project
  before_action :set_rfq, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @rfq = Rfq.new
  end

  def create
    @rfq = Rfq.new(rfq_params)
    if @rfq.save
      flash[:success] = 'Successfully created RFQ'
      redirect_to project_rfq_path(@project, @rfq)
    else
      flash[:error] = 'Something went wrong, can not create RFQ'
      redirect_to new_project_rfq_path(@project)
    end
  end

  def edit
  end

  def update
    if @rfq.update(rfq_params)
      flash[:success] = 'Successfully updated RFQ'
      redirect_to project_rfq_path(@project, @rfq)
    else
      flash[:error] = 'Something went wrong, can not update RFQ'
      redirect_to edit_project_rfq_path(@project, @rfq)
    end
  end

  def destroy
    if @rfq.destroy
      flash[:success] = 'Successfully deleted RFQ'
      redirect_to project_path(@project)
    else

    end
  end

  private

  def rfq_params
    params.require(:rfq).permit(:project_id, :name, :number, :initiator,
                                :issue_date, :due_date, :status, :sealed)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_rfq
    @rfq = Rfq.find(params[:id])
  end
end

app/controllers/super_admin/dashboard_controller.rb
class SuperAdmin::DashboardController < ApplicationController
  def index
    #code
  end
end

app/controllers/super_admin/roles_controller.rb
class SuperAdmin::RolesController < ApplicationController
  before_action :set_role, only: [:edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      flash[:success] = 'Successfully create a new role'
      redirect_to super_admin_roles_path
    else
      flash[:error] = 'Something went wrong, can not create role'
      redirect_to new_super_admin_role_path
    end
  end

  def edit
  end

  def update
    if @role.update(role_params)
      flash[:success] = 'Successfully updated role'
      redirect_to super_admin_roles_path
    else
      flash[:error] = 'Something went wrong, can not update role'
      redirect_to edit_super_admin_role_path(@role)
    end
  end

  def destroy
    if @role.destroy
      flash[:success] = 'Successfully deleted a role'
      redirect_to super_admin_roles_path
    else
      flash[:error] = 'Something went wrong, can not delete role'
      redirect_to super_admin_roles_path
    end
  end

  private

  def role_params
    params.require(:role).permit(:name)
  end

  def set_role
    @role = Role.find(params[:id])
  end
end

app/controllers/super_admin/users_controller.rb
class SuperAdmin::UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH = {
    success: 'alert-primary',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }.freeze

  def flash_messages
    flash.each do |msg_type, message|
      alert_class = BOOTSTRAP_FLASH[msg_type.to_sym]
      concat(
        content_tag(:div, message, class: "m-4 alert #{alert_class} fade-out", role: 'alert') do # rubocop:disable LineLength
          concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' }) # rubocop:disable LineLength
          concat message
        end
      )
    end
    nil
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rfqs_helper.rb
module RfqsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rfqrocket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:400,700" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/flash_notices' %>
    <div id="side-navigation">
      <%= render 'shared/side_navigation' %>
    </div>
    <div id="main-content">
      <div class="container-fluid">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= link_to "Sign In", new_user_session_path %>

app/views/projects/_form_fields.html.erb
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :name, "Project Name" %></h5>
  <%= f.text_field :name, placeholder: "Project Name", class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :number, "Project Number" %></h5>
  <%= f.text_field :number, placeholder: "Project Number", class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :jobsite, "Project Jobsite" %></h5>
  <%= f.text_field :jobsite, placeholder: "Project Jobsite", class: "form-control" %>
</div>

app/views/projects/edit.html.erb
<div class="row py-5">
  <div class="col-md-6 offset-3">
    <h2 class="text-center">Edit Project</h2>
    <%= form_with model: @project do |f| %>
      <%= render 'form_fields', f:f %>
      <div class="py-2 text-center">
        <%= f.submit "Update Project", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row py-2">
  <div class="col-md-12">
    <header>
      <h2>Projects</h2>
      <%= link_to "Add New Project", new_project_path %>
    </header>
  </div>
</div>
<div class="row py-2">
  <div class="col-md-12 table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Project Name</th>
          <th>Project Number</th>
          <th>Jobsite</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each_with_index do |project, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= project.name %></td>
            <td><%= project.number %></td>
            <td><%= project.jobsite %></td>
            <td>
              <%= link_to "View", project_path(project) %> |
              <%= link_to "Edit", edit_project_path(project) %> |
              <%= link_to "Delete", project_path(project), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row py-5">
  <div class="col-md-6 offset-3">
    <h2 class="text-center">New Project</h2>
    <%= form_with model: @project do |f| %>
      <%= render "form_fields", f:f %>
      <div class="py-2 text-center">
        <%= f.submit "Create Project", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row py-2 pt-5">
  <div class="col-md-12">
    <header>
      <h2><%= @project.name %></h2>
      <h5><%= @project.number %></h5>
      <p><strong>Jobsite:</strong> <%= @project.jobsite %></p>
      <%= link_to "Back", :back %> |
      <%= link_to "Add New RFQ", new_project_rfq_path(@project) %>
    </header>
  </div>
</div>
<div class="row py-2">
  <div class="col-md-12 table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>RFQ Name</th>
          <th>RFQ Number</th>
          <th>RFQ Initiator</th>
          <th>Status</th>
          <th>Issue Date</th>
          <th>Due Date</th>
          <th>Sealed?</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @project.rfqs.each_with_index do |rfq, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= rfq.name %></td>
            <td><%= rfq.number %></td>
            <td><%= rfq.initiator %></td>
            <td><%= rfq.status %></td>
            <td><%= rfq.issue_date %></td>
            <td><%= rfq.due_date %></td>
            <td><%= rfq.sealed %></td>
            <td>
              <%= link_to "View", project_rfq_path(@project, rfq) %> |
              <%= link_to "Edit", edit_project_rfq_path(@project, rfq) %> |
              <%= link_to "Delete", project_rfq_path(@project, rfq), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rfqs/_form_fields.html.erb
<%= f.hidden_field :project_id, {value: @project.id} %>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :status, "RFQ Status" %></h5>
  <%= f.select :status, options_for_select(Rfq::STATUS, selected: @rfq.status), { include_blank: "Status"}, class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :sealed, "RFQ Sealed?" %></h5>
  <%= f.select :sealed, options_for_select([['Sealed RFQ', true], ['Open RFQ', false]]), { include_blank: "RFQ Sealed?"}, class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :name, "RFQ Name" %></h5>
  <%= f.text_field :name, placeholder: "RFQ Name", class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :number, "RFQ Number" %></h5>
  <%= f.text_field :number, placeholder: "RFQ Number", class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :initiator, "Initiator" %></h5>
  <%= f.text_field :initiator, placeholder: "Initiator", class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :issue_date, "Issue Date" %></h5>
  <%= f.datetime_field :issue_date, placeholder: "Issue Date", class: "form-control" %>
</div>
<div class="py-2">
  <h5 class="mb-0 pb-0"><%= f.label :due_date, "Due Date" %></h5>
  <%= f.datetime_field :due_date, placeholder: "Due Date", class: "form-control" %>
</div>

app/views/rfqs/edit.html.erb
<div class="row py-5">
  <div class="col-md-6 offset-3">
    <h2 class="text-center">Edit RFQ</h2>
    <%= form_with model: [@project, @rfq] do |f| %>
      <%= render 'form_fields', f:f %>
      <div class="py-2 text-center">
        <%= f.submit "Update RFQ", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rfqs/new.html.erb
<div class="row py-5">
  <div class="col-md-6 offset-3">
    <h2 class="text-center">New RFQ</h2>
    <%= form_with model: [@project, @rfq] do |f| %>
      <%= render 'form_fields', f:f %>
      <div class="py-2 text-center">
        <%= f.submit "Create RFQ", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rfqs/show.html.erb
<div class="row py-2 pt-5">
  <div class="col-md-12">
    <header class="row">
      <div class="col-md-4">
        <h2><%= @project.name %></h2>
        <h5><%= @project.number %></h5>
        <p><strong>Jobsite:</strong> <%= @project.jobsite %></p>
        <%= link_to "Back", :back %>
      </div>
      <div class="col-md-4">
        <h3><%= @rfq.name %></h3>
        <h5><%= @rfq.number %></h5>
        <p><strong>Initiator:</strong> <%= @rfq.initiator %></p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Issue Date:</strong> <%= @rfq.issue_date %><br />
          <strong>Due Date:</strong> <%= @rfq.due_date %><br />
          <strong>Status:</strong> <%= @rfq.status %><br />
          <strong>Sealed?:</strong> <%= @rfq.sealed %>
        </p>
      </div>
    </header>
  </div>
</div>

app/views/shared/_flash_notices.html.erb
<% if flash.any? %>
<div id="flash-notices">
  <div class="container-fluid">
    <div class="col-md-8 offset-2">
      <%= flash_messages %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_side_navigation.html.erb
<%= image_tag "rocket.png", class: "img-fluid" %>
<div class="text-center">
  <%= link_to projects_path, class: "side-nav-link" do %>
    <%= fa_icon "cubes" %>
  <% end %>
</div>

app/views/super_admin/dashboard/index.html.erb
SuperAdmin Dashboard

app/views/super_admin/roles/edit.html.erb
<div class="row py-5">
  <div class="col-md-6 offset-3">
    <h2 class="text-center">Edit Role</h2>
    <%= form_with model: [:super_admin, @role] do |f| %>
    <div class="py-2">
      <h5 class="mb-0 pb-0"><%= f.label :name, "Role Name" %></h5>
      <%= f.text_field :name, placeholder: "Role Name", class: "form-control" %>
    </div>
    <div class="py-2 text-center">
      <%= f.submit "Update Role", class: "btn btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/super_admin/roles/index.html.erb
<div class="row py-2">
  <div class="col-md-12">
    <header>
      <h2>Roles</h2>
      <%= link_to "Add New Role", new_super_admin_role_path %>
    </header>
  </div>
</div>
<div class="row py-2">
  <div class="col-md-12 table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @roles.each_with_index do |role, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= role.name %></td>
            <td>
              <%= link_to "Edit", edit_super_admin_role_path(role) %> |
              <%= link_to "Delete", super_admin_role_path(role), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/super_admin/roles/new.html.erb
<div class="row py-5">
  <div class="col-md-6 offset-3">
    <h2 class="text-center">New Role</h2>
    <%= form_with model: [:super_admin, @role] do |f| %>
    <div class="py-2">
      <h5 class="mb-0 pb-0"><%= f.label :name, "Role Name" %></h5>
      <%= f.text_field :name, placeholder: "Role Name", class: "form-control" %>
    </div>
    <div class="py-2 text-center">
      <%= f.submit "Create Role", class: "btn btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/super_admin/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/super_admin/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/super_admin/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/super_admin/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>